# Generated by Django 4.2.2 on 2023-06-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(default=' ')),
                ('created', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=50)),
                ('comments', models.TextField(default='')),
            ],
        ),
    ]
